version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'accounting_challenge_api_db'
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3307:3306'
    volumes:
      - my-db:/var/lib/mysql
  web:
    depends_on:
       - "db"
    build: .
    ports:
       - "3000:3000"
    environment:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: accounting_challenge_api_db
      DB_PORT: 3306
      DB_HOST: db
      RAILS_ENV: development
    volumes:
       - ".:/app"
    expose:
      - '3000'
volumes:
  my-db: